/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 1.0.0-rc.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export * from './apis/apiapi';
export * from './apis/authentication-api';
export * from './apis/composite-api';
export * from './apis/default-api';
export * from './apis/games-api';
export * from './apis/lists-api';
export * from './apis/messages-api';
export * from './apis/news-api';
export * from './apis/ratings-api';
export * from './apis/reports-api';
export * from './apis/reviews-api';
export * from './apis/screenshots-api';
export * from './apis/tags-api';
export * from './apis/users-api';

