/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import globalAxios, { AxiosResponse, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
import { APIError } from '../models';
import { Game &amp; any } from '../models';
import { InlineResponse2003 } from '../models';
import { InlineResponse2004 } from '../models';
import { List } from '../models';
/**
 * ListsApi - axios parameter creator
 * @export
 */
export const ListsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Remove a Game from being bookmarked
         * @summary Remove a Game from being bookmarked
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteBookmarkedGame: async (authorization: string, gid: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling deleteBookmarkedGame.');
            }
            // verify required parameter 'gid' is not null or undefined
            if (gid === null || gid === undefined) {
                throw new RequiredError('gid','Required parameter gid was null or undefined when calling deleteBookmarkedGame.');
            }
            const localVarPath = `/lists/bookmark/{gid}`
                .replace(`{${"gid"}}`, encodeURIComponent(String(gid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove a Game from being cleared
         * @summary Remove a Game from being cleared
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteClearedGame: async (authorization: string, gid: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling deleteClearedGame.');
            }
            // verify required parameter 'gid' is not null or undefined
            if (gid === null || gid === undefined) {
                throw new RequiredError('gid','Required parameter gid was null or undefined when calling deleteClearedGame.');
            }
            const localVarPath = `/lists/clear/{gid}`
                .replace(`{${"gid"}}`, encodeURIComponent(String(gid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Remove a Game from being favorited
         * @summary Remove a Game from being favorited
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteFavoritedGame: async (authorization: string, gid: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling deleteFavoritedGame.');
            }
            // verify required parameter 'gid' is not null or undefined
            if (gid === null || gid === undefined) {
                throw new RequiredError('gid','Required parameter gid was null or undefined when calling deleteFavoritedGame.');
            }
            const localVarPath = `/lists/favorite/{gid}`
                .replace(`{${"gid"}}`, encodeURIComponent(String(gid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Delete List (User/Admin Only)
         * @summary Delete List (User/Admin Only)
         * @param {string} authorization 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteList: async (authorization: string, id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling deleteList.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling deleteList.');
            }
            const localVarPath = `/lists/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Bookmark List Contents
         * @summary Get Bookmark List Contents
         * @param {string} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBookmarkedGames: async (authorization: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling getBookmarkedGames.');
            }
            const localVarPath = `/lists/bookmarks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Clear List Contents
         * @summary Get Clear List Contents
         * @param {number} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getClearListGames: async (uid: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uid' is not null or undefined
            if (uid === null || uid === undefined) {
                throw new RequiredError('uid','Required parameter uid was null or undefined when calling getClearListGames.');
            }
            const localVarPath = `/lists/clears/{uid}`
                .replace(`{${"uid"}}`, encodeURIComponent(String(uid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Favorites List Contents
         * @summary Get Favorites List Contents
         * @param {number} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFavoritesListGames: async (uid: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'uid' is not null or undefined
            if (uid === null || uid === undefined) {
                throw new RequiredError('uid','Required parameter uid was null or undefined when calling getFavoritesListGames.');
            }
            const localVarPath = `/lists/favorites/{uid}`
                .replace(`{${"uid"}}`, encodeURIComponent(String(uid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Following List Contents
         * @summary Get Following List Contents
         * @param {string} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFollowingUsers: async (authorization: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling getFollowingUsers.');
            }
            const localVarPath = `/lists/following`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get Games from Owner
         * @summary Get Games from Owner
         * @param {number} ownerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getGamesByOwner: async (ownerId: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ownerId' is not null or undefined
            if (ownerId === null || ownerId === undefined) {
                throw new RequiredError('ownerId','Required parameter ownerId was null or undefined when calling getGamesByOwner.');
            }
            const localVarPath = `/lists/owned/{ownerId}`
                .replace(`{${"ownerId"}}`, encodeURIComponent(String(ownerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Check if User has Game bookmarked
         * @summary Check if User has a Game bookmarked
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIsGameBookmarked: async (authorization: string, gid: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling getIsGameBookmarked.');
            }
            // verify required parameter 'gid' is not null or undefined
            if (gid === null || gid === undefined) {
                throw new RequiredError('gid','Required parameter gid was null or undefined when calling getIsGameBookmarked.');
            }
            const localVarPath = `/lists/bookmark/{gid}`
                .replace(`{${"gid"}}`, encodeURIComponent(String(gid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Check if User has Game cleared
         * @summary Check if User has a Game cleared
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIsGameCleared: async (authorization: string, gid: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling getIsGameCleared.');
            }
            // verify required parameter 'gid' is not null or undefined
            if (gid === null || gid === undefined) {
                throw new RequiredError('gid','Required parameter gid was null or undefined when calling getIsGameCleared.');
            }
            const localVarPath = `/lists/clear/{gid}`
                .replace(`{${"gid"}}`, encodeURIComponent(String(gid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Check if User has Game favorited
         * @summary Check if User has a Game favorited
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getIsGameFavorited: async (authorization: string, gid: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling getIsGameFavorited.');
            }
            // verify required parameter 'gid' is not null or undefined
            if (gid === null || gid === undefined) {
                throw new RequiredError('gid','Required parameter gid was null or undefined when calling getIsGameFavorited.');
            }
            const localVarPath = `/lists/favorite/{gid}`
                .replace(`{${"gid"}}`, encodeURIComponent(String(gid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get List
         * @summary Get List
         * @param {string} authorization 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getList: async (authorization: string, id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling getList.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getList.');
            }
            const localVarPath = `/lists/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Get List Contents
         * @summary Get List Contents
         * @param {string} authorization 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getListGames: async (authorization: string, id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling getListGames.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling getListGames.');
            }
            const localVarPath = `/lists/{id}/games`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Update List (User/Admin Only)
         * @summary Update List (User/Admin Only)
         * @param {string} authorization 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchList: async (authorization: string, id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling patchList.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling patchList.');
            }
            const localVarPath = `/lists/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {List} body 
         * @param {string} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postList: async (body: List, authorization: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling postList.');
            }
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling postList.');
            }
            const localVarPath = `/lists`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Add Game to Bookmarks
         * @summary Add Game to Bookmarks
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putBookmarkGame: async (authorization: string, gid: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling putBookmarkGame.');
            }
            // verify required parameter 'gid' is not null or undefined
            if (gid === null || gid === undefined) {
                throw new RequiredError('gid','Required parameter gid was null or undefined when calling putBookmarkGame.');
            }
            const localVarPath = `/lists/bookmark/{gid}`
                .replace(`{${"gid"}}`, encodeURIComponent(String(gid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Add Game to Clear
         * @summary Add Game to Clear
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putClearGame: async (authorization: string, gid: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling putClearGame.');
            }
            // verify required parameter 'gid' is not null or undefined
            if (gid === null || gid === undefined) {
                throw new RequiredError('gid','Required parameter gid was null or undefined when calling putClearGame.');
            }
            const localVarPath = `/lists/clear/{gid}`
                .replace(`{${"gid"}}`, encodeURIComponent(String(gid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Add Game to Favorites
         * @summary Add Game to Favorites
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putFavoriteGame: async (authorization: string, gid: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling putFavoriteGame.');
            }
            // verify required parameter 'gid' is not null or undefined
            if (gid === null || gid === undefined) {
                throw new RequiredError('gid','Required parameter gid was null or undefined when calling putFavoriteGame.');
            }
            const localVarPath = `/lists/favorite/{gid}`
                .replace(`{${"gid"}}`, encodeURIComponent(String(gid)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
        /**
         * Replace Games in List (User/Admin Only)
         * @summary Replace Games in List (User/Admin Only)
         * @param {any} body 
         * @param {string} authorization 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putList: async (body: any, authorization: string, id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            if (body === null || body === undefined) {
                throw new RequiredError('body','Required parameter body was null or undefined when calling putList.');
            }
            // verify required parameter 'authorization' is not null or undefined
            if (authorization === null || authorization === undefined) {
                throw new RequiredError('authorization','Required parameter authorization was null or undefined when calling putList.');
            }
            // verify required parameter 'id' is not null or undefined
            if (id === null || id === undefined) {
                throw new RequiredError('id','Required parameter id was null or undefined when calling putList.');
            }
            const localVarPath = `/lists/{id}/games`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, 'https://example.com');
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }
            const localVarRequestOptions :AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            if (configuration && configuration.accessToken) {
                const accessToken = typeof configuration.accessToken === 'function'
                    ? await configuration.accessToken()
                    : await configuration.accessToken;
                localVarHeaderParameter["Authorization"] = "Bearer " + accessToken;
            }

            if (authorization !== undefined && authorization !== null) {
                localVarHeaderParameter['Authorization'] = String(authorization);
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';

            const query = new URLSearchParams(localVarUrlObj.search);
            for (const key in localVarQueryParameter) {
                query.set(key, localVarQueryParameter[key]);
            }
            for (const key in options.params) {
                query.set(key, options.params[key]);
            }
            localVarUrlObj.search = (new URLSearchParams(query)).toString();
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            const needsSerialization = (typeof body !== "string") || localVarRequestOptions.headers['Content-Type'] === 'application/json';
            localVarRequestOptions.data =  needsSerialization ? JSON.stringify(body !== undefined ? body : {}) : (body || "");

            return {
                url: localVarUrlObj.pathname + localVarUrlObj.search + localVarUrlObj.hash,
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ListsApi - functional programming interface
 * @export
 */
export const ListsApiFp = function(configuration?: Configuration) {
    return {
        /**
         * Remove a Game from being bookmarked
         * @summary Remove a Game from being bookmarked
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteBookmarkedGame(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).deleteBookmarkedGame(authorization, gid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Remove a Game from being cleared
         * @summary Remove a Game from being cleared
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteClearedGame(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).deleteClearedGame(authorization, gid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Remove a Game from being favorited
         * @summary Remove a Game from being favorited
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteFavoritedGame(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).deleteFavoritedGame(authorization, gid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Delete List (User/Admin Only)
         * @summary Delete List (User/Admin Only)
         * @param {string} authorization 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteList(authorization: string, id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).deleteList(authorization, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get Bookmark List Contents
         * @summary Get Bookmark List Contents
         * @param {string} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBookmarkedGames(authorization: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<InlineResponse2003>>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).getBookmarkedGames(authorization, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get Clear List Contents
         * @summary Get Clear List Contents
         * @param {number} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getClearListGames(uid: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<InlineResponse2003>>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).getClearListGames(uid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get Favorites List Contents
         * @summary Get Favorites List Contents
         * @param {number} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFavoritesListGames(uid: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<InlineResponse2003>>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).getFavoritesListGames(uid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get Following List Contents
         * @summary Get Following List Contents
         * @param {string} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFollowingUsers(authorization: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<InlineResponse2004>>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).getFollowingUsers(authorization, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get Games from Owner
         * @summary Get Games from Owner
         * @param {number} ownerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGamesByOwner(ownerId: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array<Game & any>>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).getGamesByOwner(ownerId, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Check if User has Game bookmarked
         * @summary Check if User has a Game bookmarked
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getIsGameBookmarked(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<boolean>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).getIsGameBookmarked(authorization, gid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Check if User has Game cleared
         * @summary Check if User has a Game cleared
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getIsGameCleared(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<boolean>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).getIsGameCleared(authorization, gid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Check if User has Game favorited
         * @summary Check if User has a Game favorited
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getIsGameFavorited(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<boolean>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).getIsGameFavorited(authorization, gid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get List
         * @summary Get List
         * @param {string} authorization 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getList(authorization: string, id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).getList(authorization, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Get List Contents
         * @summary Get List Contents
         * @param {string} authorization 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getListGames(authorization: string, id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).getListGames(authorization, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Update List (User/Admin Only)
         * @summary Update List (User/Admin Only)
         * @param {string} authorization 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchList(authorization: string, id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).patchList(authorization, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * 
         * @param {List} body 
         * @param {string} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postList(body: List, authorization: string, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<Array>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).postList(body, authorization, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Add Game to Bookmarks
         * @summary Add Game to Bookmarks
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putBookmarkGame(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).putBookmarkGame(authorization, gid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Add Game to Clear
         * @summary Add Game to Clear
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putClearGame(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).putClearGame(authorization, gid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Add Game to Favorites
         * @summary Add Game to Favorites
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putFavoriteGame(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).putFavoriteGame(authorization, gid, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
        /**
         * Replace Games in List (User/Admin Only)
         * @summary Replace Games in List (User/Admin Only)
         * @param {any} body 
         * @param {string} authorization 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putList(body: any, authorization: string, id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => Promise<AxiosResponse<void>>> {
            const localVarAxiosArgs = await ListsApiAxiosParamCreator(configuration).putList(body, authorization, id, options);
            return (axios: AxiosInstance = globalAxios, basePath: string = BASE_PATH) => {
                const axiosRequestArgs :AxiosRequestConfig = {...localVarAxiosArgs.options, url: basePath + localVarAxiosArgs.url};
                return axios.request(axiosRequestArgs);
            };
        },
    }
};

/**
 * ListsApi - factory interface
 * @export
 */
export const ListsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    return {
        /**
         * Remove a Game from being bookmarked
         * @summary Remove a Game from being bookmarked
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteBookmarkedGame(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return ListsApiFp(configuration).deleteBookmarkedGame(authorization, gid, options).then((request) => request(axios, basePath));
        },
        /**
         * Remove a Game from being cleared
         * @summary Remove a Game from being cleared
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteClearedGame(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return ListsApiFp(configuration).deleteClearedGame(authorization, gid, options).then((request) => request(axios, basePath));
        },
        /**
         * Remove a Game from being favorited
         * @summary Remove a Game from being favorited
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteFavoritedGame(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return ListsApiFp(configuration).deleteFavoritedGame(authorization, gid, options).then((request) => request(axios, basePath));
        },
        /**
         * Delete List (User/Admin Only)
         * @summary Delete List (User/Admin Only)
         * @param {string} authorization 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteList(authorization: string, id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return ListsApiFp(configuration).deleteList(authorization, id, options).then((request) => request(axios, basePath));
        },
        /**
         * Get Bookmark List Contents
         * @summary Get Bookmark List Contents
         * @param {string} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBookmarkedGames(authorization: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<InlineResponse2003>>> {
            return ListsApiFp(configuration).getBookmarkedGames(authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Get Clear List Contents
         * @summary Get Clear List Contents
         * @param {number} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getClearListGames(uid: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<InlineResponse2003>>> {
            return ListsApiFp(configuration).getClearListGames(uid, options).then((request) => request(axios, basePath));
        },
        /**
         * Get Favorites List Contents
         * @summary Get Favorites List Contents
         * @param {number} uid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFavoritesListGames(uid: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<InlineResponse2003>>> {
            return ListsApiFp(configuration).getFavoritesListGames(uid, options).then((request) => request(axios, basePath));
        },
        /**
         * Get Following List Contents
         * @summary Get Following List Contents
         * @param {string} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFollowingUsers(authorization: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<InlineResponse2004>>> {
            return ListsApiFp(configuration).getFollowingUsers(authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Get Games from Owner
         * @summary Get Games from Owner
         * @param {number} ownerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getGamesByOwner(ownerId: number, options?: AxiosRequestConfig): Promise<AxiosResponse<Array<Game & any>>> {
            return ListsApiFp(configuration).getGamesByOwner(ownerId, options).then((request) => request(axios, basePath));
        },
        /**
         * Check if User has Game bookmarked
         * @summary Check if User has a Game bookmarked
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getIsGameBookmarked(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<AxiosResponse<boolean>> {
            return ListsApiFp(configuration).getIsGameBookmarked(authorization, gid, options).then((request) => request(axios, basePath));
        },
        /**
         * Check if User has Game cleared
         * @summary Check if User has a Game cleared
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getIsGameCleared(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<AxiosResponse<boolean>> {
            return ListsApiFp(configuration).getIsGameCleared(authorization, gid, options).then((request) => request(axios, basePath));
        },
        /**
         * Check if User has Game favorited
         * @summary Check if User has a Game favorited
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getIsGameFavorited(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<AxiosResponse<boolean>> {
            return ListsApiFp(configuration).getIsGameFavorited(authorization, gid, options).then((request) => request(axios, basePath));
        },
        /**
         * Get List
         * @summary Get List
         * @param {string} authorization 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getList(authorization: string, id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return ListsApiFp(configuration).getList(authorization, id, options).then((request) => request(axios, basePath));
        },
        /**
         * Get List Contents
         * @summary Get List Contents
         * @param {string} authorization 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getListGames(authorization: string, id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return ListsApiFp(configuration).getListGames(authorization, id, options).then((request) => request(axios, basePath));
        },
        /**
         * Update List (User/Admin Only)
         * @summary Update List (User/Admin Only)
         * @param {string} authorization 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchList(authorization: string, id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return ListsApiFp(configuration).patchList(authorization, id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {List} body 
         * @param {string} authorization 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postList(body: List, authorization: string, options?: AxiosRequestConfig): Promise<AxiosResponse<Array>> {
            return ListsApiFp(configuration).postList(body, authorization, options).then((request) => request(axios, basePath));
        },
        /**
         * Add Game to Bookmarks
         * @summary Add Game to Bookmarks
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putBookmarkGame(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return ListsApiFp(configuration).putBookmarkGame(authorization, gid, options).then((request) => request(axios, basePath));
        },
        /**
         * Add Game to Clear
         * @summary Add Game to Clear
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putClearGame(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return ListsApiFp(configuration).putClearGame(authorization, gid, options).then((request) => request(axios, basePath));
        },
        /**
         * Add Game to Favorites
         * @summary Add Game to Favorites
         * @param {string} authorization 
         * @param {number} gid 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putFavoriteGame(authorization: string, gid: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return ListsApiFp(configuration).putFavoriteGame(authorization, gid, options).then((request) => request(axios, basePath));
        },
        /**
         * Replace Games in List (User/Admin Only)
         * @summary Replace Games in List (User/Admin Only)
         * @param {any} body 
         * @param {string} authorization 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putList(body: any, authorization: string, id: number, options?: AxiosRequestConfig): Promise<AxiosResponse<void>> {
            return ListsApiFp(configuration).putList(body, authorization, id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ListsApi - object-oriented interface
 * @export
 * @class ListsApi
 * @extends {BaseAPI}
 */
export class ListsApi extends BaseAPI {
    /**
     * Remove a Game from being bookmarked
     * @summary Remove a Game from being bookmarked
     * @param {string} authorization 
     * @param {number} gid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async deleteBookmarkedGame(authorization: string, gid: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return ListsApiFp(this.configuration).deleteBookmarkedGame(authorization, gid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Remove a Game from being cleared
     * @summary Remove a Game from being cleared
     * @param {string} authorization 
     * @param {number} gid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async deleteClearedGame(authorization: string, gid: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return ListsApiFp(this.configuration).deleteClearedGame(authorization, gid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Remove a Game from being favorited
     * @summary Remove a Game from being favorited
     * @param {string} authorization 
     * @param {number} gid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async deleteFavoritedGame(authorization: string, gid: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return ListsApiFp(this.configuration).deleteFavoritedGame(authorization, gid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Delete List (User/Admin Only)
     * @summary Delete List (User/Admin Only)
     * @param {string} authorization 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async deleteList(authorization: string, id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return ListsApiFp(this.configuration).deleteList(authorization, id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get Bookmark List Contents
     * @summary Get Bookmark List Contents
     * @param {string} authorization 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async getBookmarkedGames(authorization: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<InlineResponse2003>>> {
        return ListsApiFp(this.configuration).getBookmarkedGames(authorization, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get Clear List Contents
     * @summary Get Clear List Contents
     * @param {number} uid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async getClearListGames(uid: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<InlineResponse2003>>> {
        return ListsApiFp(this.configuration).getClearListGames(uid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get Favorites List Contents
     * @summary Get Favorites List Contents
     * @param {number} uid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async getFavoritesListGames(uid: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<InlineResponse2003>>> {
        return ListsApiFp(this.configuration).getFavoritesListGames(uid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get Following List Contents
     * @summary Get Following List Contents
     * @param {string} authorization 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async getFollowingUsers(authorization: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<InlineResponse2004>>> {
        return ListsApiFp(this.configuration).getFollowingUsers(authorization, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get Games from Owner
     * @summary Get Games from Owner
     * @param {number} ownerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async getGamesByOwner(ownerId: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array<Game & any>>> {
        return ListsApiFp(this.configuration).getGamesByOwner(ownerId, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Check if User has Game bookmarked
     * @summary Check if User has a Game bookmarked
     * @param {string} authorization 
     * @param {number} gid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async getIsGameBookmarked(authorization: string, gid: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<boolean>> {
        return ListsApiFp(this.configuration).getIsGameBookmarked(authorization, gid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Check if User has Game cleared
     * @summary Check if User has a Game cleared
     * @param {string} authorization 
     * @param {number} gid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async getIsGameCleared(authorization: string, gid: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<boolean>> {
        return ListsApiFp(this.configuration).getIsGameCleared(authorization, gid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Check if User has Game favorited
     * @summary Check if User has a Game favorited
     * @param {string} authorization 
     * @param {number} gid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async getIsGameFavorited(authorization: string, gid: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<boolean>> {
        return ListsApiFp(this.configuration).getIsGameFavorited(authorization, gid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get List
     * @summary Get List
     * @param {string} authorization 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async getList(authorization: string, id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return ListsApiFp(this.configuration).getList(authorization, id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Get List Contents
     * @summary Get List Contents
     * @param {string} authorization 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async getListGames(authorization: string, id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return ListsApiFp(this.configuration).getListGames(authorization, id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Update List (User/Admin Only)
     * @summary Update List (User/Admin Only)
     * @param {string} authorization 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async patchList(authorization: string, id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return ListsApiFp(this.configuration).patchList(authorization, id, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * 
     * @param {List} body 
     * @param {string} authorization 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async postList(body: List, authorization: string, options?: AxiosRequestConfig) : Promise<AxiosResponse<Array>> {
        return ListsApiFp(this.configuration).postList(body, authorization, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Add Game to Bookmarks
     * @summary Add Game to Bookmarks
     * @param {string} authorization 
     * @param {number} gid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async putBookmarkGame(authorization: string, gid: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return ListsApiFp(this.configuration).putBookmarkGame(authorization, gid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Add Game to Clear
     * @summary Add Game to Clear
     * @param {string} authorization 
     * @param {number} gid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async putClearGame(authorization: string, gid: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return ListsApiFp(this.configuration).putClearGame(authorization, gid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Add Game to Favorites
     * @summary Add Game to Favorites
     * @param {string} authorization 
     * @param {number} gid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async putFavoriteGame(authorization: string, gid: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return ListsApiFp(this.configuration).putFavoriteGame(authorization, gid, options).then((request) => request(this.axios, this.basePath));
    }
    /**
     * Replace Games in List (User/Admin Only)
     * @summary Replace Games in List (User/Admin Only)
     * @param {any} body 
     * @param {string} authorization 
     * @param {number} id 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ListsApi
     */
    public async putList(body: any, authorization: string, id: number, options?: AxiosRequestConfig) : Promise<AxiosResponse<void>> {
        return ListsApiFp(this.configuration).putList(body, authorization, id, options).then((request) => request(this.axios, this.basePath));
    }
}
