/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 1.0.0-rc.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface AuthResponse
 */
export interface AuthResponse {

    /**
     * @type {number}
     * @memberof AuthResponse
     */
    id: number;

    /**
     * @type {string}
     * @memberof AuthResponse
     */
    name: string;

    /**
     * @type {string}
     * @memberof AuthResponse
     */
    phash2: string;

    /**
     * @type {string}
     * @memberof AuthResponse
     */
    dateCreated: string;

    /**
     * @type {string}
     * @memberof AuthResponse
     */
    twitchLink?: string;

    /**
     * @type {string}
     * @memberof AuthResponse
     */
    youtubeLink?: string;

    /**
     * @type {string}
     * @memberof AuthResponse
     */
    nicoLink?: string;

    /**
     * @type {string}
     * @memberof AuthResponse
     */
    twitterLink?: string;

    /**
     * @type {string}
     * @memberof AuthResponse
     */
    bio?: string;

    /**
     * @type {boolean}
     * @memberof AuthResponse
     */
    isAdmin: boolean;

    /**
     * @type {string}
     * @memberof AuthResponse
     */
    email?: string;

    /**
     * @type {boolean}
     * @memberof AuthResponse
     */
    banned: boolean;

    /**
     * @type {number}
     * @memberof AuthResponse
     */
    selectedBadge?: number;

    /**
     * @type {string}
     * @memberof AuthResponse
     */
    token: string;
}
