/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 2.0.0-rc0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { GameExtRatings } from './game-ext-ratings';
import { GameExtTag } from './game-ext-tag';
import { Review } from './review';
import { Screenshot } from './screenshot';
 /**
 * 
 *
 * @export
 * @interface GameExt
 */
export interface GameExt {

    /**
     * @type {number}
     * @memberof GameExt
     */
    id?: number;

    /**
     * @type {string}
     * @memberof GameExt
     */
    name?: string;

    /**
     * @type {string}
     * @memberof GameExt
     */
    sortname?: string;

    /**
     * @type {string}
     * @memberof GameExt
     */
    url?: string;

    /**
     * @type {string}
     * @memberof GameExt
     */
    urlSpdrn?: string;

    /**
     * @type {Array<string>}
     * @memberof GameExt
     */
    author?: Array<string>;

    /**
     * @type {string}
     * @memberof GameExt
     */
    authorRaw?: string;

    /**
     * @type {boolean}
     * @memberof GameExt
     */
    collab?: boolean;

    /**
     * @type {string}
     * @memberof GameExt
     */
    dateCreated?: string;

    /**
     * @type {string}
     * @memberof GameExt
     */
    adderId?: string;

    /**
     * @type {boolean}
     * @memberof GameExt
     */
    removed?: boolean;

    /**
     * @type {string}
     * @memberof GameExt
     */
    ownerId?: string;

    /**
     * @type {string}
     * @memberof GameExt
     */
    ownerBio?: string;

    /**
     * @type {GameExtRatings}
     * @memberof GameExt
     */
    ratings: GameExtRatings;

    /**
     * @type {Array<Review>}
     * @memberof GameExt
     */
    reviews: Array<Review>;

    /**
     * @type {Array<GameExtTag>}
     * @memberof GameExt
     */
    tags: Array<GameExtTag>;

    /**
     * @type {Array<Screenshot>}
     * @memberof GameExt
     */
    screenshots: Array<Screenshot>;
}
