/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 2.0.0-rc0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Game
 */
export interface Game {

    /**
     * @type {number}
     * @memberof Game
     */
    id?: number;

    /**
     * @type {string}
     * @memberof Game
     */
    name?: string;

    /**
     * @type {string}
     * @memberof Game
     */
    sortname?: string;

    /**
     * @type {string}
     * @memberof Game
     */
    url?: string;

    /**
     * @type {string}
     * @memberof Game
     */
    urlSpdrn?: string;

    /**
     * @type {Array<string>}
     * @memberof Game
     */
    author?: Array<string>;

    /**
     * @type {string}
     * @memberof Game
     */
    authorRaw?: string;

    /**
     * @type {boolean}
     * @memberof Game
     */
    collab?: boolean;

    /**
     * @type {string}
     * @memberof Game
     */
    dateCreated?: string;

    /**
     * @type {string}
     * @memberof Game
     */
    adderId?: string;

    /**
     * @type {boolean}
     * @memberof Game
     */
    removed?: boolean;

    /**
     * @type {string}
     * @memberof Game
     */
    ownerId?: string;

    /**
     * @type {string}
     * @memberof Game
     */
    ownerBio?: string;
}
