/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 1.0.0-rc.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GameExtTag
 */
export interface GameExtTag {

    /**
     * @type {string}
     * @memberof GameExtTag
     */
    name: string;

    /**
     * @type {number}
     * @memberof GameExtTag
     */
    id: number;

    /**
     * @type {number}
     * @memberof GameExtTag
     */
    count: number;
}
