/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 2.0.0-rc0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GameExtRatings
 */
export interface GameExtRatings {

    /**
     * @type {number}
     * @memberof GameExtRatings
     */
    difficulty: number;

    /**
     * @type {number}
     * @memberof GameExtRatings
     */
    rating: number;
}
