/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetReportParams
 */
export interface GetReportParams {

    /**
     * @type {number}
     * @memberof GetReportParams
     */
    page?: number;

    /**
     * @type {number}
     * @memberof GetReportParams
     */
    limit?: number;

    /**
     * @type {string}
     * @memberof GetReportParams
     */
    orderCol?: string;

    /**
     * @type {string}
     * @memberof GetReportParams
     */
    orderDir?: GetReportParamsOrderDirEnum;

    /**
     * @type {number}
     * @memberof GetReportParams
     */
    id?: number;

    /**
     * @type {string}
     * @memberof GetReportParams
     */
    type?: string;

    /**
     * @type {boolean}
     * @memberof GetReportParams
     */
    answered?: boolean;
}

/**
 * @export
 * @enum {string}
 */
export enum GetReportParamsOrderDirEnum {
    ASC = 'ASC',
    DESC = 'DESC'
}

