/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 2.0.0-rc0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface GetScreenshotParms
 */
export interface GetScreenshotParms {

    /**
     * @type {number}
     * @memberof GetScreenshotParms
     */
    gameId?: number;

    /**
     * @type {boolean}
     * @memberof GetScreenshotParms
     */
    removed?: boolean;

    /**
     * @type {boolean}
     * @memberof GetScreenshotParms
     */
    approved?: boolean;

    /**
     * @type {number}
     * @memberof GetScreenshotParms
     */
    page?: number;

    /**
     * @type {number}
     * @memberof GetScreenshotParms
     */
    limit?: number;

    /**
     * @type {number}
     * @memberof GetScreenshotParms
     */
    id?: number;

    /**
     * @type {number}
     * @memberof GetScreenshotParms
     */
    addedById?: number;
}
