/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface News
 */
export interface News {

    /**
     * @type {number}
     * @memberof News
     */
    id?: number;

    /**
     * @type {number}
     * @memberof News
     */
    posterId?: number;

    /**
     * @type {string}
     * @memberof News
     */
    title?: string;

    /**
     * @type {string}
     * @memberof News
     */
    _short?: string;

    /**
     * @type {string}
     * @memberof News
     */
    news?: string;

    /**
     * @type {string}
     * @memberof News
     */
    dateCreated?: string;

    /**
     * @type {boolean}
     * @memberof News
     */
    removed?: boolean;
}
