/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * From T, pick a set of properties whose keys are in the union K
 *
 * @export
 * @interface PickUserExcludeKeyofUserEmailOrIsAdminOrCanReportOrCanSubmitOrCanReviewOrCanScreenshotOrBanned_
 */
export interface PickUserExcludeKeyofUserEmailOrIsAdminOrCanReportOrCanSubmitOrCanReviewOrCanScreenshotOrBanned_ {

    /**
     * @type {number}
     * @memberof PickUserExcludeKeyofUserEmailOrIsAdminOrCanReportOrCanSubmitOrCanReviewOrCanScreenshotOrBanned_
     */
    id: number;

    /**
     * @type {string}
     * @memberof PickUserExcludeKeyofUserEmailOrIsAdminOrCanReportOrCanSubmitOrCanReviewOrCanScreenshotOrBanned_
     */
    name: string;

    /**
     * @type {Date}
     * @memberof PickUserExcludeKeyofUserEmailOrIsAdminOrCanReportOrCanSubmitOrCanReviewOrCanScreenshotOrBanned_
     */
    dateCreated: Date;

    /**
     * @type {boolean}
     * @memberof PickUserExcludeKeyofUserEmailOrIsAdminOrCanReportOrCanSubmitOrCanReviewOrCanScreenshotOrBanned_
     */
    canMessage?: boolean;

    /**
     * @type {string}
     * @memberof PickUserExcludeKeyofUserEmailOrIsAdminOrCanReportOrCanSubmitOrCanReviewOrCanScreenshotOrBanned_
     */
    twitchLink: string;

    /**
     * @type {string}
     * @memberof PickUserExcludeKeyofUserEmailOrIsAdminOrCanReportOrCanSubmitOrCanReviewOrCanScreenshotOrBanned_
     */
    nicoLink: string;

    /**
     * @type {string}
     * @memberof PickUserExcludeKeyofUserEmailOrIsAdminOrCanReportOrCanSubmitOrCanReviewOrCanScreenshotOrBanned_
     */
    youtubeLink: string;

    /**
     * @type {string}
     * @memberof PickUserExcludeKeyofUserEmailOrIsAdminOrCanReportOrCanSubmitOrCanReviewOrCanScreenshotOrBanned_
     */
    twitterLink: string;

    /**
     * @type {string}
     * @memberof PickUserExcludeKeyofUserEmailOrIsAdminOrCanReportOrCanSubmitOrCanReviewOrCanScreenshotOrBanned_
     */
    bio: string;

    /**
     * @type {number}
     * @memberof PickUserExcludeKeyofUserEmailOrIsAdminOrCanReportOrCanSubmitOrCanReviewOrCanScreenshotOrBanned_
     */
    selectedBadge: number;
}
