/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 1.0.0-rc.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * From T, pick a set of properties whose keys are in the union K
 *
 * @export
 * @interface PickUserExtExcludeKeyofUserExtRatingsCountOrScreenshotCount_
 */
export interface PickUserExtExcludeKeyofUserExtRatingsCountOrScreenshotCount_ {

    /**
     * @type {number}
     * @memberof PickUserExtExcludeKeyofUserExtRatingsCountOrScreenshotCount_
     */
    id: number;

    /**
     * @type {string}
     * @memberof PickUserExtExcludeKeyofUserExtRatingsCountOrScreenshotCount_
     */
    name: string;

    /**
     * @type {string}
     * @memberof PickUserExtExcludeKeyofUserExtRatingsCountOrScreenshotCount_
     */
    dateCreated: string;

    /**
     * @type {string}
     * @memberof PickUserExtExcludeKeyofUserExtRatingsCountOrScreenshotCount_
     */
    twitchLink?: string;

    /**
     * @type {string}
     * @memberof PickUserExtExcludeKeyofUserExtRatingsCountOrScreenshotCount_
     */
    nicoLink?: string;

    /**
     * @type {string}
     * @memberof PickUserExtExcludeKeyofUserExtRatingsCountOrScreenshotCount_
     */
    youtubeLink?: string;

    /**
     * @type {string}
     * @memberof PickUserExtExcludeKeyofUserExtRatingsCountOrScreenshotCount_
     */
    twitterLink?: string;

    /**
     * @type {string}
     * @memberof PickUserExtExcludeKeyofUserExtRatingsCountOrScreenshotCount_
     */
    bio?: string;

    /**
     * @type {number}
     * @memberof PickUserExtExcludeKeyofUserExtRatingsCountOrScreenshotCount_
     */
    selectedBadge?: number;

    /**
     * @type {string}
     * @memberof PickUserExtExcludeKeyofUserExtRatingsCountOrScreenshotCount_
     */
    token: string;

    /**
     * @type {number}
     * @memberof PickUserExtExcludeKeyofUserExtRatingsCountOrScreenshotCount_
     */
    reviewCount: number;

    /**
     * @type {boolean}
     * @memberof PickUserExtExcludeKeyofUserExtRatingsCountOrScreenshotCount_
     */
    isFollowing: boolean;
}
