/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Message } from './message';
 /**
 * 
 *
 * @export
 * @interface PostMessageParams
 */
export interface PostMessageParams {

    /**
     * @type {string}
     * @memberof PostMessageParams
     */
    cfTurnstileResponse: string;

    /**
     * @type {number}
     * @memberof PostMessageParams
     */
    id?: number;

    /**
     * @type {boolean}
     * @memberof PostMessageParams
     */
    isRead?: boolean;

    /**
     * @type {number}
     * @memberof PostMessageParams
     */
    userFromId?: number;

    /**
     * @type {number}
     * @memberof PostMessageParams
     */
    userToId?: number;

    /**
     * @type {string}
     * @memberof PostMessageParams
     */
    subject?: string;

    /**
     * @type {string}
     * @memberof PostMessageParams
     */
    body?: string;

    /**
     * @type {string}
     * @memberof PostMessageParams
     */
    dateCreated?: string;

    /**
     * @type {boolean}
     * @memberof PostMessageParams
     */
    deleted?: boolean;

    /**
     * @type {number}
     * @memberof PostMessageParams
     */
    replyToId?: number;

    /**
     * @type {number}
     * @memberof PostMessageParams
     */
    threadId?: number;
}
