/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Report
 */
export interface Report {

    /**
     * @type {number}
     * @memberof Report
     */
    id?: number;

    /**
     * @type {string}
     * @memberof Report
     */
    type?: ReportTypeEnum;

    /**
     * @type {number}
     * @memberof Report
     */
    targetId?: number;

    /**
     * @type {string}
     * @memberof Report
     */
    report?: string;

    /**
     * @type {number}
     * @memberof Report
     */
    reporterId?: number;

    /**
     * @type {string}
     * @memberof Report
     */
    reporterName?: string;

    /**
     * @type {number}
     * @memberof Report
     */
    answeredById?: number;

    /**
     * @type {string}
     * @memberof Report
     */
    answeredByName?: string;

    /**
     * @type {string}
     * @memberof Report
     */
    dateCreated?: string;

    /**
     * @type {string}
     * @memberof Report
     */
    dateAnswered?: string;
}

/**
 * @export
 * @enum {string}
 */
export enum ReportTypeEnum {
    Game = 'game',
    GameAdd = 'game_add',
    GameRemove = 'game_remove',
    GameUpdateUrl = 'game_update_url',
    GameUpdateOwner = 'game_update_owner',
    GameUpdateCreator = 'game_update_creator',
    GameUpdate = 'game_update',
    User = 'user',
    UserRegister = 'user_register',
    UserPasswordChange = 'user_password_change',
    Review = 'review',
    ReviewRestore = 'review_restore',
    Screenshot = 'screenshot',
    ScreenshotRemove = 'screenshot_remove'
}

