/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { HttpStatusCodeLiteral } from './http-status-code-literal';
import { URL } from './url';
 /**
 * Make all properties in T required
 *
 * @export
 * @interface RequiredTypeURLTitleStringStatusHttpStatusCodeLiteralDetailStringInstanceURL_
 */
export interface RequiredTypeURLTitleStringStatusHttpStatusCodeLiteralDetailStringInstanceURL_ {

    /**
     * @type {URL}
     * @memberof RequiredTypeURLTitleStringStatusHttpStatusCodeLiteralDetailStringInstanceURL_
     */
    type: URL;

    /**
     * @type {string}
     * @memberof RequiredTypeURLTitleStringStatusHttpStatusCodeLiteralDetailStringInstanceURL_
     */
    title: string;

    /**
     * @type {HttpStatusCodeLiteral}
     * @memberof RequiredTypeURLTitleStringStatusHttpStatusCodeLiteralDetailStringInstanceURL_
     */
    status: HttpStatusCodeLiteral;

    /**
     * @type {string}
     * @memberof RequiredTypeURLTitleStringStatusHttpStatusCodeLiteralDetailStringInstanceURL_
     */
    detail: string;

    /**
     * @type {URL}
     * @memberof RequiredTypeURLTitleStringStatusHttpStatusCodeLiteralDetailStringInstanceURL_
     */
    instance: URL;
}
