/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface Screenshot
 */
export interface Screenshot {

    /**
     * @type {number}
     * @memberof Screenshot
     */
    id?: number;

    /**
     * @type {number}
     * @memberof Screenshot
     */
    gameId?: number;

    /**
     * @type {number}
     * @memberof Screenshot
     */
    addedById?: number;

    /**
     * @type {number}
     * @memberof Screenshot
     */
    approvedById?: number;

    /**
     * @type {string}
     * @memberof Screenshot
     */
    description?: string;

    /**
     * @type {boolean}
     * @memberof Screenshot
     */
    approved?: boolean;

    /**
     * @type {string}
     * @memberof Screenshot
     */
    dateCreated?: string;

    /**
     * @type {boolean}
     * @memberof Screenshot
     */
    removed?: boolean;
}
