/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 1.0.0-rc.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * The **`URL`** interface is used to parse, construct, normalize, and encode URL.  [MDN Reference](https://developer.mozilla.org/docs/Web/API/URL)
 *
 * @export
 * @interface URL
 */
export interface URL {
}
