/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 1.0.0-rc.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { Email } from './email';
 /**
 * 
 *
 * @export
 * @interface User
 */
export interface User {

    /**
     * @type {Email}
     * @memberof User
     */
    email?: Email;

    /**
     * @type {boolean}
     * @memberof User
     */
    banned?: boolean;

    /**
     * @type {number}
     * @memberof User
     */
    selectedBadge: number;

    /**
     * @type {string}
     * @memberof User
     */
    bio: string;

    /**
     * @type {string}
     * @memberof User
     */
    twitterLink: string;

    /**
     * @type {string}
     * @memberof User
     */
    youtubeLink: string;

    /**
     * @type {string}
     * @memberof User
     */
    nicoLink: string;

    /**
     * @type {string}
     * @memberof User
     */
    twitchLink: string;

    /**
     * @type {boolean}
     * @memberof User
     */
    canMessage?: boolean;

    /**
     * @type {boolean}
     * @memberof User
     */
    canScreenshot?: boolean;

    /**
     * @type {boolean}
     * @memberof User
     */
    canReview?: boolean;

    /**
     * @type {boolean}
     * @memberof User
     */
    canSubmit?: boolean;

    /**
     * @type {boolean}
     * @memberof User
     */
    canReport?: boolean;

    /**
     * @type {boolean}
     * @memberof User
     */
    isAdmin?: boolean;

    /**
     * @type {Date}
     * @memberof User
     */
    dateCreated: Date;

    /**
     * @type {string}
     * @memberof User
     */
    name: string;

    /**
     * @type {number}
     * @memberof User
     */
    id: number;
}
