/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 1.0.0-rc.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UserPermissions
 */
export interface UserPermissions {

    /**
     * @type {boolean}
     * @memberof UserPermissions
     */
    canMessage: boolean;

    /**
     * @type {boolean}
     * @memberof UserPermissions
     */
    canScreenshot: boolean;

    /**
     * @type {boolean}
     * @memberof UserPermissions
     */
    canReview: boolean;

    /**
     * @type {boolean}
     * @memberof UserPermissions
     */
    canSubmit: boolean;

    /**
     * @type {boolean}
     * @memberof UserPermissions
     */
    canReport: boolean;
}
