/* tslint:disable */
/* eslint-disable */
/**
 * Delicious Fruit API
 * The API you should use instead of throwing your monitor out the window
 *
 * OpenAPI spec version: 1.0.0-rc.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface UserRegistration
 */
export interface UserRegistration {

    /**
     * @type {string}
     * @memberof UserRegistration
     */
    username: string;

    /**
     * @type {string}
     * @memberof UserRegistration
     */
    password: string;

    /**
     * @type {string}
     * @memberof UserRegistration
     */
    email: string;
}
